// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dimocks

import (
	"github.com/folder-app/internal/app/usecase"
	mock "github.com/stretchr/testify/mock"
)

// NewDI creates a new instance of DI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDI(t interface {
	mock.TestingT
	Cleanup(func())
}) *DI {
	mock := &DI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DI is an autogenerated mock type for the DI type
type DI struct {
	mock.Mock
}

type DI_Expecter struct {
	mock *mock.Mock
}

func (_m *DI) EXPECT() *DI_Expecter {
	return &DI_Expecter{mock: &_m.Mock}
}

// ProvideFoldersRepository provides a mock function for the type DI
func (_mock *DI) ProvideFoldersRepository() usecase.Repository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProvideFoldersRepository")
	}

	var r0 usecase.Repository
	if returnFunc, ok := ret.Get(0).(func() usecase.Repository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(usecase.Repository)
		}
	}
	return r0
}

// DI_ProvideFoldersRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProvideFoldersRepository'
type DI_ProvideFoldersRepository_Call struct {
	*mock.Call
}

// ProvideFoldersRepository is a helper method to define mock.On call
func (_e *DI_Expecter) ProvideFoldersRepository() *DI_ProvideFoldersRepository_Call {
	return &DI_ProvideFoldersRepository_Call{Call: _e.mock.On("ProvideFoldersRepository")}
}

func (_c *DI_ProvideFoldersRepository_Call) Run(run func()) *DI_ProvideFoldersRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DI_ProvideFoldersRepository_Call) Return(repository usecase.Repository) *DI_ProvideFoldersRepository_Call {
	_c.Call.Return(repository)
	return _c
}

func (_c *DI_ProvideFoldersRepository_Call) RunAndReturn(run func() usecase.Repository) *DI_ProvideFoldersRepository_Call {
	_c.Call.Return(run)
	return _c
}
