// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dimocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewDI creates a new instance of DI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDI(t interface {
	mock.TestingT
	Cleanup(func())
}) *DI {
	mock := &DI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DI is an autogenerated mock type for the DI type
type DI struct {
	mock.Mock
}

type DI_Expecter struct {
	mock *mock.Mock
}

func (_m *DI) EXPECT() *DI_Expecter {
	return &DI_Expecter{mock: &_m.Mock}
}

// ProvideHTTPMux provides a mock function for the type DI
func (_mock *DI) ProvideHTTPMux() *http.ServeMux {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProvideHTTPMux")
	}

	var r0 *http.ServeMux
	if returnFunc, ok := ret.Get(0).(func() *http.ServeMux); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.ServeMux)
		}
	}
	return r0
}

// DI_ProvideHTTPMux_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProvideHTTPMux'
type DI_ProvideHTTPMux_Call struct {
	*mock.Call
}

// ProvideHTTPMux is a helper method to define mock.On call
func (_e *DI_Expecter) ProvideHTTPMux() *DI_ProvideHTTPMux_Call {
	return &DI_ProvideHTTPMux_Call{Call: _e.mock.On("ProvideHTTPMux")}
}

func (_c *DI_ProvideHTTPMux_Call) Run(run func()) *DI_ProvideHTTPMux_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DI_ProvideHTTPMux_Call) Return(serveMux *http.ServeMux) *DI_ProvideHTTPMux_Call {
	_c.Call.Return(serveMux)
	return _c
}

func (_c *DI_ProvideHTTPMux_Call) RunAndReturn(run func() *http.ServeMux) *DI_ProvideHTTPMux_Call {
	_c.Call.Return(run)
	return _c
}
